---
title: "ML EDA"
output: html_document
date: "2023-04-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Exploratory Data Analysis - Nutritional Values

# Structure and summary
```{r}

# Now let's see the structure of our data
recipes_raw %>% 
  head(20) %>% 
  str() 

# We have only numerical variables, but in reality just 4 variables could be considered as such. More in particular, "rating", "calories", "protein", "fat" and "sodium" could be considered as such. The other variables should be considered as a categorical variable since they allow only for 0 or 1 values.


# Let's have a different look at the data with the summary function.
recipes_raw %>% 
  select(rating, calories, protein, fat, sodium) %>% 
  dfSummary(style = "grid")

# We can already see for instance that the majority of the values of the variable "rating" are 4.38 (40% of the total). Moreover, we observe that the variables "calories", "protein", "fat" and "sodium" have roughly 20% of missing values.

```

## Visual exploration - Univariate Analysis

# Rating Barplot
```{r}

recipes_raw %>% 
  ggplot(aes(x=as.factor(rating), fill=as.factor(rating) )) +  
  geom_bar( ) +
  scale_fill_manual(values = c("red4", "red3", "orangered", "orange", "gold", "greenyellow", "green3", "green4") ) +
  theme(legend.position="none") +
  scale_y_continuous(breaks=seq(0,10000,1000)) +
  labs(x = "Rating", y = "Count", 
       title = "Overview of recipes' ratings")

# As we can see, most of the ratings have value above 3.75
# A zero rating indicates that the recipe has not been evaluated yet.

```

# Calories - Protein - Fat - Sodium  Boxplots
```{r}

recipes_raw_boxplot <-
  recipes_raw %>% 
  pivot_longer(cols = c(calories, protein, fat, sodium),
               names_to = "nutrition",
               values_to = "n_value")

recipes_raw_calories <- recipes_raw_boxplot %>% 
  filter(nutrition == "calories")

recipes_raw_calories %>%
  ggplot( aes(x=nutrition, y=n_value, fill=nutrition)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
    theme_light() +
    theme(legend.position="none",
          plot.title = element_text(size=11)) +
  ggtitle("Basic boxplot") +
  xlab("") +
  ylab("Value")
  

# We notice that there are values above 10'000'000 which are clearly outliers. We must then discard those values in order to continue with a meaningful analysis. At this stage, from a visual point of view we cannot extract any relevant information.

recipes_raw_calories %>% 
  select(title, nutrition, n_value) %>% 
  arrange(desc(n_value)) 

recipes_raw_boxplot <- recipes_raw_boxplot %>% 
  filter(n_value <= 2500)

recipes_raw_boxplot %>%
  ggplot( aes(x=nutrition, y=n_value, fill=nutrition)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
    theme_light() +
    theme(legend.position="none",
          plot.title = element_text(size=11)) +
  ggtitle("Basic boxplot") +
  xlab("") +
  ylab("Value")

```


# Calories - Protein - Fat - Sodium  Histograms
```{r}

# Calories histogram

recipes_raw %>% 
  filter(calories != "NA") %>% 
  ggplot(aes(x=calories)) +
  geom_histogram(binwidth=3, fill="red3", color="red3", alpha=0.9) +
  ggtitle("Calories Distribution") +
  theme(plot.title = element_text(size=15))

recipes_raw_plot <- epi_r %>% 
  filter(calories <= 10000)

recipes_raw_plot %>% 
  ggplot(aes(x=calories)) +
  geom_histogram(binwidth=50, fill="red3", color="red3", alpha=0.9) +
  ggtitle("Calories Distribution") +
  theme(plot.title = element_text(size=15)) +
  scale_x_continuous(breaks=seq(0,10000,1000))

# Most of the recipes have an amount of calories which is below 1500.

```



# Visual exploration - multivariate analysis
```{r}


```


